baseURL = "http://glyndarkin.co.uk/"
languageCode = "en-us"
title = "Glyn Darkin"
theme = [ "minimal"]
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Glyn Darkin"
    description = "This is me, I live in Dublin, Ireland. I love making stuff, going places and having adventures"
    githubUsername = "#"
    accent = "#4799B7"
    showBorder = true
    backgroundColor = "white"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    


#[[menu.main]]
#    url = "/"
#    name = "home"
#    weight = 1

#[[menu.main]]
#    url = "/work/"
#    name = "#work"
#    weight = 2

#[[menu.main]]
#    url = "/make/"
#    name = "#make"
#    weight = 3

#[[menu.main]]
#    url = "/do/"
#    name = "#do"
#    weight = 4


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@glyndarkin.co.uk"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/glyndarkin/"
    name = "instagram"
    weight = 2


[[menu.icon]]
    url = "https://twitter.com/glyndarkin"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/glyndarkin/"
    name = "linkedin"
    weight = 5

#[[menu.icon]]
 #   url = "https://www.stackoverflow.com/username/"
 #   name = "stack-overflow"
 #   weight = 5
